In [1]:
import numpy as np
import pandas as pd

In [4]:
datos = pd.DataFrame({
    'hours_sleep':[1,2,3,4,5,6,7],
    'attendance':[60,65,70,75,80,85,87],
    'grades':[50,65,70,75,np.nan,85,np.nan]
})

datos

,hours_sleep,attendance,grades
0,1,60,50.0
1,2,65,65.0
2,3,70,70.0
3,4,75,75.0
4,5,80,NaN
5,6,85,85.0
6,7,87,NaN


In [7]:
from sklearn.linear_model import LinearRegression

In [15]:
train_df = datos[datos['grades'].notnull()]
train_df
missing_df = datos[datos['grades'].isnull()]
missing_df
x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']

#fit regression
modelo = LinearRegression()
modelo.fit(x_train,y_train)

x_test = missing_df[['hours_sleep', 'attendance']]
predict = modelo.predict(x_test)
predict


array([80.67567568, 89.90644491])

In [ ]:
# single imputation
data_filled = datos.copy()
data_filled.loc[data_filled['grades'].isnull(), 'grades'] = predict
data_filled

,hours_sleep,attendance,grades
0,1,60,50.000000
1,2,65,65.000000
2,3,70,70.000000
3,4,75,75.000000
4,5,80,80.675676
5,6,85,85.000000
6,7,87,89.906445


In [18]:
#bayesian regression
from sklearn.linear_model import BayesianRidge

In [25]:
train_df = datos[datos['grades'].notnull()]
missing_df = datos[datos['grades'].isnull()]
x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']

bayesian_model = BayesianRidge()
bayesian_model.fit(x_train, y_train)

x_test = missing_df[['hours_sleep', 'attendance']]
predict2 = bayesian_model.predict(x_test)
predict2

#computing the uncertanties
predict2, std = bayesian_model.predict(x_test, return_std=True)

# print(predict2 , std)
for predict, uncert in zip(predict2, std):
    print('predict', predict)
    print('uncertanty', uncert)


predict 80.45396941441557
uncertanty 3.789951707447654
predict 89.50945805401761
uncertanty 4.529439480000733


In [51]:
# challenge:
# generate differente values for imputation

aleatorios1 = np.random.normal(loc=predict2[0], scale=std.iloc[0], size=100)
aleatorios2 = np.random.normal(loc=predict2[1], scale=std.iloc[1], size=100)

-------

In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import BayesianRidge

In [15]:
datos = pd.DataFrame({
    'hours_sleep':[1,2,3,4,5,6,7],
    'attendance':[60,65,70,75,80,85,87],
    'grades':[50,65,70,75,np.nan,85,np.nan]
})

datos


,hours_sleep,attendance,grades
0,1,60,50.0
1,2,65,65.0
2,3,70,70.0
3,4,75,75.0
4,5,80,NaN
5,6,85,85.0
6,7,87,NaN


In [16]:
train_df = datos[datos['grades'].notnull()]
train_df
missing_df = datos[datos['grades'].isnull()]
missing_df
x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']

In [17]:
bayesian_model = BayesianRidge()
bayesian_model.fit(x_train, y_train)

x_test = missing_df[['hours_sleep', 'attendance']]
predict2 = bayesian_model.predict(x_test)
predict2

#computing the uncertanties
predict2, std = bayesian_model.predict(x_test, return_std=True)

# print(predict2 , std)
for predict, uncert in zip(predict2, std):
    print('predict', predict)
    print('uncertanty', uncert)

predict 80.45396941441557
uncertanty 3.789951707447654
predict 89.50945805401761
uncertanty 4.529439480000733


In [18]:
m = 3
np.random.seed(42)

aleatorios1 = np.random.normal(loc=predict2[0], scale=std.iloc[0], size=m)
aleatorios2 = np.random.normal(loc=predict2[1], scale=std.iloc[1], size=m)
print(aleatorios1)
print(aleatorios2)

[82.33649207 79.92995439 82.9086777 ]
[96.40792961 88.44887451 88.44894888]


In [9]:
df1 = datos.copy()
df1.loc[df1['grades'].isnull(), 'grades'] = [aleatorios1[0], aleatorios2[0]]
df1

,hours_sleep,attendance,grades
0,1,60,50.000000
1,2,65,65.000000
2,3,70,70.000000
3,4,75,75.000000
4,5,80,82.336492
5,6,85,85.000000
6,7,87,96.407930


In [20]:
def mult_imputation(data, m):
    dfs = {}
    for j in range(m):
        dfm = data.copy()
        dfm.loc[dfm['grades'].isnull(), 'grades'] = [aleatorios1[j], aleatorios2[j]]
        dfs[f'df_{j}'] = dfm
    return dfs

ds = mult_imputation(datos, m)
ds

{'df_0':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  82.336492
 5            6          85  85.000000
 6            7          87  96.407930,
 'df_1':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  79.929954
 5            6          85  85.000000
 6            7          87  88.448875,
 'df_2':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  82.908678
 5            6          85  85.000000
 6            7          87  88.448949}

------

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import BayesianRidge

In [21]:
datos = pd.DataFrame({
    'hours_sleep':[1,2,3,4,5,6,7],
    'attendance':[60,65,70,75,80,85,87],
    'grades':[50,65,70,75,np.nan,85,np.nan]
})

datos

,hours_sleep,attendance,grades
0,1,60,50.0
1,2,65,65.0
2,3,70,70.0
3,4,75,75.0
4,5,80,NaN
5,6,85,85.0
6,7,87,NaN


In [31]:
train_df = datos[datos['grades'].notnull()]
missing_df = datos[datos['grades'].isnull()]

x_train = train_df[['hours_sleep', 'attendance']]
y_train = train_df['grades']
x_test = missing_df[['hours_sleep', 'attendance']]

bayesian_model = BayesianRidge()
bayesian_model.fit(x_train, y_train)

predict_mean, predict_std = bayesian_model.predict(x_test, return_std=True)

np.random.seed(42)

def mult_imputation(data, means, stds, m=3):
    dfs = {}
    for j in range(m):
        dfm = data.copy()
        random_imputes = np.random.normal(loc=means, scale=stds)
        
        dfm.loc[dfm['grades'].isnull(), 'grades'] = random_imputes
        dfs[f'df_{j}'] = dfm
        
    return dfs

ds = mult_imputation(datos, predict_mean, predict_std, m=3)
ds


{'df_0':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  82.336492
 5            6          85  85.000000
 6            7          87  88.883198,
 'df_1':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  82.908678
 5            6          85  85.000000
 6            7          87  96.407930,
 'df_2':    hours_sleep  attendance     grades
 0            1          60  50.000000
 1            2          65  65.000000
 2            3          70  70.000000
 3            4          75  75.000000
 4            5          80  79.566539
 5            6          85  85.000000
 6            7          87  88.448949}

### compute within and between quantities for the last example and interpret.


### what is the objective of bayessian regression and the difference with "usual" linear regression
### what we are computing in bayessian regression?
- bayessian regression
- posterior distribution in bayessian regression
- conditional expected value in bayessian regression
- linear regression. expected value for impoutation


In [24]:
within_sample_mean = []
for i in range(m):
    prom = float(ds[f'df_{i}']['grades'].mean())
    within_sample_mean.append(prom)

within_sample_mean = np.array(within_sample_mean)
within_sample_mean


array([73.74567005, 74.90237247, 73.2879269 ])

In [25]:
pool_mean = float(np.sum(within_sample_mean/m))
pool_mean

73.9786564740977

In [26]:
within_sample_variance = []
for i in range(m):
    variance = float(ds[f'df_{i}']['grades'].var())
    within_sample_variance.append(variance)

within_sample_variance = np.array(within_sample_variance)
within_sample_variance

array([180.92565077, 228.46331922, 171.86819137])

In [30]:
between_imputation = np.sum((within_sample_mean-pool_mean)**2) / (m-1)
between_imputation



np.float64(3.1814239285571846)

In [32]:
total_variance = np.mean(within_sample_variance) + (1+1/m)*between_imputation
total_variance

np.float64(195.4969031282012)